### PR TITLE
Add Two Numbers

### PR DESCRIPTION
**Pull request by shubhangi-dwivedi**
Please merge the PR.

### CODE REVIEW

**Comment by avijitsen7076** [comment]
do start to get it merged! pls

**Comment by avijitsen7076** [comment]
No its okay just star the repo ;)

**Comment by arin2002** [comment]
can i do this please

**Comment by avijitsen7076** [comment]
> can i do this please

create another pr bro

**Comment by avijitsen7076** [comment]
@shubhangi-dwivedi star the repo pls!

**Pull request merged**
